## to fetch the secrets created using secrets.yaml file you can use this file

## create the file using ubectl create -f secret-env.yaml

## check the values once pod created using  kubectl exec -it secret-env-pod env | grep SECRET_

apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
    - name: mycontainer
      image: alpine:latest
      command: ["sleep", "9999"]
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: password
  restartPolicy: Never
